### ISSUE TITLE
decode returns imageType as "image/xxx"

### ISSUE THREAD

**Issue by andyli** [DiegoZoracKy/image-data-uri#8]
README says `decode()` returns something like `imageType: 'png'`, but in reality, it is `imageType: 'image/png'`.

The regexp should be changed from `(image/.*)` to `image/(.*)` in

https://github.com/DiegoZoracKy/image-data-uri/blob/af2fa12b9b3d5264f2f9534b4d8f95129f189f73/lib/image-data-uri.js#L24-L29

**Comment by DiegoZoracKy** [comment]
Hi @andyli ,

Sorry for this late reply, and thanks for catching that. In fact, the wrong piece here is the documentation. The expected result is indeed the mimeType, which would be written as `image/*` in this case.

**Comment by DiegoZoracKy** [comment]
New version published already to **npm**.

Thanks @andyli
